services:
  app:
    image: "sjc.vultrcr.com/dongregistry/hls_converter:latest"
    container_name: hls_converter-${BUILD_BRANCH}
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 9573
    volumes:
      - ./.env:/home/node/.env
      - ./logs:/home/node/logs
      - /home/dong/files/video:/home/node/video
      - /home/dong/files/hls:/home/node/hls
    networks:
      - proxy

networks:
  proxy:
    external: true
