services:
  app:
    image: "sjc.vultrcr.com/dongregistry/hls_converter:latest"
    # build:
      # context: .
      # dockerfile: Dockerfile
    container_name: hls_converter-${BUILD_BRANCH}
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5000
    # ports:
    #   - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./.env:/home/node/.env
      - ./logs:/home/node/logs
        # 호스트의 FFmpeg 바이너리 마운트
      - /usr/bin/ffmpeg:/usr/bin/ffmpeg:ro
      # FFmpeg 관련 공유 라이브러리 마운트 (Ubuntu/Debian 기준)
      - /usr/lib:/usr/lib:ro
      - /lib:/lib:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
